site_name: LM Markdown for Education

plugins:
  - search
  - mkdocstrings

theme:
  name: material
  font:
    text: Merriweather
    code: Fira Code
  palette:
    - scheme: default
      primary: slate
      accent: custom

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Handbook:
    - Installation and quickstart: Handbook/Installation.md
    - RAG authoring: Handbook/RAGauthoring.md
    - Working with Markdown: Handbook/Markdown.md
    - Encoding and Embedding: Handbook/EncodingEmbedding.md
    - Main Chatbot: Handbook/ChatApp.md
    - Configuration: Handbook/Configuration.md
  - Architecture:
    - Overview: Architecture/Overview.md
    - Outline Architecture: Architecture/Architecture.md
    - Outline Implementation: Architecture/Implementation.md
  - API:
    - Configuration:
      - Configuration modules:  API/Configuration/index.md
      - Module config.py: API/Configuration/config.md
      - Module appchat.py: API/Configuration/appchat.md
    - Apps:
      - Apps: API/Apps/index.md
      - App Chat: API/Apps/appChat.md
      - App Webcast: API/Apps/appWebcast.md
    - Utilities:
      - App Base: API/appbase.md
      - App Utils: API/apputils.md
      - Background Task Manager: API/background_task_manager.md
      - Logging DB: API/logging_db.md
    - CLI:
      - LMME: API/cli_lmme.md
      - Terminal: API/cli_terminal.md
    - RAG:
      - Module scan_rag.py: API/scan_rag.md
      - Module ingest.py: API/ingest.md
      - Module querydb.py: API/querydb.md
      - Module query.py: API/query.md
    - LMM Workflows:
      - Workflows and graphs:
        - Architecture: API/workflows.md
        - Base: API/workflow_base.md
        - Workflow: API/chat_workflow.md
        - Agent: API/chat_agent.md
        - Workflow factory: API/workflow_factory.md
      - Streams:
        - Stream adapters: API/stream_adapters.md
        - Chat stream adapters: API/chat_stream_adapters.md
    - Vector Stores:
      - Module vector_store_qdrant.py: API/vector_store_qdrant.md
      - Module vector_store_qdrant_langchain.py: API/vector_store_qdrant_langchain.md
      - Module vector store context: API/vector_store_qdrant_context.md
      - Utilities: API/vector_store_qdrant_utils.md
